### PR TITLE
HttpContext for issue #8

### PR DESCRIPTION
**Pull request by manureini**

### CODE REVIEW

**Comment by manureini** [comment]
HttpContext for issue #8

**Comment by tpeczek** [comment]
Hi,

Thank you for your pull request, I will review it in details as soon as possible, but before I do that I have a general question. What is your primary interest in `HttpContext`? My gut feeling is that you are accessing `HttpRequest` as it has the most useful information. If that's the case (and in most scenarios it probably will be), it might be better to expose it as more firendly API approach (and it will still leave a way to access `HttpContext` through `HttpRequest`). What is your opinion?

**Comment by manureini** [comment]
I'm using it like this:

int channelId = Convert.ToInt32(e.HttpContext.Request.Query["id"]);

I'm very new to Asp.Net so I'm really used with it.

If you can get the query parameters with HttpRequest, too I don't care ;)

**Comment by tpeczek** [comment]
So that `HttpContext.Request` is `HttpRequest`. And this is exactly what I'm expecting, that must of the time that `.Request` property would be accessed. This is why I would prefer for `HttpRequest` to be the parameter. Can you make the change before I start the review?

**Comment by manureini** [comment]
Got it ;)

**Comment by tpeczek** [comment]
Great :) I should be able to review this pull request tomorrow.

**Review by tpeczek — APPROVED** [review]
Will require cosmetic changes, but it's good enough to merge.

**Comment by tpeczek** [comment]
Merged, thank you!

**Pull request merged**
